### ISSUE TITLE
一些小问题

### ISSUE THREAD

**Issue by snikeguo** [IKende/XRPC#10]
1.有没有QQ群？
2.我在测试，大文件传输，5MB左右，提示 buffer decoding error! @The message to long!  请问有没有这样稍微大一点文件传输的例子？ 多谢。

` Hello World!
[10:12:57] [Info] Register IMyService->MyService@SetValue to /IMyService/SetValue[ThreadType:None|UniqueID:]
[10:12:57] [Info] Register IMyService->MyService@GetValue to /IMyService/GetValue[ThreadType:None|UniqueID:]
[10:12:57] [Info] Register IMyService->MyService@SetBytes to /IMyService/SetBytes[ThreadType:None|UniqueID:]
[10:12:57] [Info] Register IMyService->MyService@GetBytes to /IMyService/GetBytes[ThreadType:None|UniqueID:]
[10:12:58] [Info]
*******************************************************************************
 BeetleX xrpc service framework
 Copyright ? ikende.com 2019-2020 email:henryfan@msn.com
 ServerGC    [False]
 BeetleX     Version [1.4.8.0]
 XRPC        Version [0.8.2.3]
 -----------------------------------------------------------------------------
 Listen :9090   [SSL:False]     [Status:success]
*******************************************************************************

[10:13:06] [Error] session [::ffff:127.0.0.1]:59436@1 error [::ffff:127.0.0.1]:59436 session  buffer decoding error! @The message to long!
   at BeetleX.XRPC.RPCPacket.Read(Options rpcOption, PipeStream stream)
   at BeetleX.XRPC.Packets.ServerPacket.Decode(ISession session, Stream stream)
   at BeetleX.TcpServer.SessionReceive(SessionReceiveEventArgs e)

`

**Comment by snikeguo** [comment]
public interface IMyService
    {
        Task SetValue(int v);
        Task<int> GetValue();
        Task SetBytes(byte[] b);
        Task<byte[]> GetBytes();
    }
    [Service(typeof(IMyService))]
    public class MyService : IMyService
    {
        private int i = int.MinValue;

        public Task<byte[]> GetBytes()
        {
            return Task.FromResult(File.ReadAllBytes(@"testzip.7z"));//大概也就是5mb
        }

        public Task<int> GetValue()
        {
            return Task.FromResult(i);
        }
        
        public Task SetBytes(byte[] b)
        {
            File.WriteAllBytes(@"E:\disk\Move\VSProject\DavidLib\build\内部刷新上位机带协议解析3.7z", b);
            return Task.CompletedTask;
        }

        public Task SetValue(int v)
        {
            i = v;
            return Task.CompletedTask;
        }
    }

**Comment by snikeguo** [comment]
后来问题找到了 根据the message to long!搜索到源码的位置，添加了此语句mXRPCServer.RPCOptions.MessageMaxLength = 1024 * 1024 * 1024;

不过，大佬可否给一个简单的基于XRPC的C/S 客户端升级的DEMO？带进度条的等等。

**Comment by IKende** [comment]
你这种可以自己把文件切分包来传输，不建议把消息最大长度设置这么大。
组件暂只在issues做支持

**Comment by snikeguo** [comment]
@IKende  了解。我看到
public virtual void SessionDetection(IServer server, SessionDetectionEventArgs e)
        {
            if (e.Sesions != null)
            {
                for (int i = 0; i < e.Sesions.Count; i++)
                {
                    ISession session = (ISession)e.Sesions[i];
                    session.Dispose();
                    if (server.EnableLog(LogType.Info))
                    {
                        server.Log(LogType.Info, session, "{0} session time out", session.RemoteEndPoint);
                    }
                }
            }
        }
现有一个需求，当客户端在规定时间没没有调用远程服务的时候，服务器要把它踢掉（虽然这是两者 之间的网络仍然在线）。于是看到了上述的代码。
当服务器设置好SessionTimeout的时候，会调用这个函数。可否在for循环的Dispose之前，搞个事件广播出去？

**Comment by IKende** [comment]
对于获取token可以看 https://github.com/IKende/BeetleX-Samples/tree/master/XRPC.WFPChat 
`SessionTimeout`现阶段不要开启，因为XRPC还以接管这个时间更新，开启了可以会把有效的连接杀死。

**Comment by snikeguo** [comment]
考虑以下场景：
登录名：admin,密码123456
下面的TCP连接的   actorID都是admin
第一个TCP连接进来并登录成功，比如这个连接token是001。

第二个 也使用上述的登录名和密码且actorID都是admin(即客户端把用户名当做actorID了)，TCP连接进来并登录成功，这时候token是002

请问如何处理这种情况比较好？干掉第一个连接吗？

**Comment by snikeguo** [comment]
客户端和服务器连接后，假如有这样的需求： 服务端有一个事件，当服务端的这个事件被触发后，客户端这边会执行相应的方法 。类似于：服务器的事件委托 += 客户端的方法。  我看了twoway的demo 好像不是这种的。

**Comment by IKende** [comment]
组件暂不支持事件
