### ISSUE TITLE
Controller folder has been removed in 'src/BeetleX.XRPC.csproj'

### ISSUE THREAD

**Issue by nero-philip-wang** [IKende/XRPC#11]
Controller folder has been removed in 'src/BeetleX.XRPC.csproj' which causes ControllerAttribute cannot been compiled and the demo in README.md cannot work.

**Comment by www2sssyyy** [comment]
看了一下代码，现在那个属性已经修改到EventNext库了，但是EventNext/src/EventCenter.cs中的245行的提示不对，因为你已经改用了ServiceAttribute，而且readme的demo也还没改

**Comment by IKende** [comment]
最新文档建议看
http://doc.beetlex.io/
