### ISSUE TITLE
XRPCClient是否能提供已连接和已断开的事件，方便处理断线重连后的自定制操作。

### ISSUE THREAD

**Issue by e4ky** [IKende/XRPC#28]
XRPCClient是否能像XRPCServer一样提供已连接（RPCConnected）和已断开的（RPCDisconnect）事件，方便处理断线重连后的自定制操作。

**Comment by IKende** [comment]
有对应的Connected事件

**Comment by e4ky** [comment]
![QQ截图20200916085651](https://user-images.githubusercontent.com/11674702/93279746-9a402080-f7fa-11ea-8f80-09e5bbfb85a9.png)
并未对外提供

**Comment by e4ky** [comment]
嗯终于找到了
