### ISSUE TITLE
客户端缺少销毁或主动断连的方法

### ISSUE THREAD

**Issue by zzeric** [IKende/XRPC#37]
client = new XRPCClient("localhost", 9090);
client.Options.ParameterFormater = new JsonPacket();//default messagepack
helloSession = client.Create<IHello>();

其中client和helloSession都没有Close和Dispose

**Comment by beetlex-io** [comment]
XRPCClient是线程安全的，针对一个host定义一个即可。

**Comment by zzeric** [comment]
> XRPCClient是线程安全的，针对一个host定义一个即可。
现在XRPCClient是做了单例
那session呢?监测client对应session的TcpClient的Connencted是false，此时需要新建一个session,但旧的没有办法销毁

**Comment by beetlex-io** [comment]
旧的服务器检测到链接断开会清除
