### ISSUE TITLE
依赖注入遇见了几个问题 

### ISSUE THREAD

**Issue by nodyang** [IKende/XRPC#5]
1 由于 ServerOptions RPCOptions 都是private set 外层很难整体注入 只能通过改变其属性

![image](https://user-images.githubusercontent.com/3090191/71399147-b93fc680-265d-11ea-8d68-71b8d0c45126.png)

2 
![image](https://user-images.githubusercontent.com/3090191/71399261-002dbc00-265e-11ea-8996-ea4e315e07ed.png)
现在基于这样的方式。感觉好别扭

**Comment by IKende** [comment]
已提供了hosting插件支持DI，可以看示例
https://github.com/IKende/BeetleX-Samples
